- name: PACKAGES | INSTALL | Install APP's requirements
  apt:
    state: installed
    update_cache: yes
    pkg: "{{ item }}"
  with_items:
    - rsync
    - python
    - python-pip
    - python-dev
    - python3
    - python3-dev
    - python3-pip
    - virtualenv
    - gcc
  become: true

#- name: PACKAGES | INSTALL | Upgrade pip
#  shell: pip3 install --upgrade pip